#!/usr/bin/env bash
# 在 VPS 上从 GitHub 拉取指定提交、构建并通过 PM2 发布。
#
# 此脚本由 GitHub Actions 通过 SSH 调用，也可在 VPS 上手动执行：
#   /home/<deploy-user>/iiqe-app/scripts/deploy-pm2-from-git.sh <commit-sha>
#
# 机密、SQLite 文件与备份均存放在 APP_DIR 之外，避免 git reset / clean
# 或重新构建时覆盖生产数据。完整的初始化步骤见 DEPLOY.md。

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
DEFAULT_APP_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"

APP_DIR="${APP_DIR:-$DEFAULT_APP_DIR}"
DEPLOY_BRANCH="${DEPLOY_BRANCH:-main}"
PM2_APP_NAME="${PM2_APP_NAME:-iiqe-app}"
PORT="${PORT:-3001}"
SHARED_DIR="${SHARED_DIR:-$(dirname -- "$APP_DIR")/iiqe-shared}"
ENV_FILE="${ENV_FILE:-$SHARED_DIR/.env.production}"
DATA_DIR="${DATA_DIR:-$SHARED_DIR/data}"
BACKUP_DIR="${BACKUP_DIR:-$SHARED_DIR/backups}"
LOG_DIR="${PM2_LOG_DIR:-$SHARED_DIR/logs}"
LOCK_FILE="${LOCK_FILE:-$SHARED_DIR/deploy.lock}"
BACKUP_KEEP="${BACKUP_KEEP:-14}"
DEPLOY_SHA="${1:-}"

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1"
}

[[ "$DEPLOY_SHA" =~ ^[0-9a-fA-F]{40}$ ]] || fail "Pass the 40-character commit SHA to deploy."
[[ "$DEPLOY_BRANCH" =~ ^[A-Za-z0-9._/-]+$ ]] || fail "DEPLOY_BRANCH contains unsupported characters."
[[ "$BACKUP_KEEP" =~ ^[0-9]+$ ]] || fail "BACKUP_KEEP must be a non-negative integer."

require_command flock
require_command git
require_command npm
require_command npx
require_command node
require_command pm2
require_command curl

[[ -d "$APP_DIR/.git" ]] || fail "APP_DIR is not a Git checkout: $APP_DIR"
[[ -r "$ENV_FILE" ]] || fail "Production environment file is missing or unreadable: $ENV_FILE"

mkdir -p "$SHARED_DIR" "$DATA_DIR" "$BACKUP_DIR" "$LOG_DIR"
exec 9>"$LOCK_FILE"
flock -n 9 || fail "Another deployment is already running."

# shellcheck disable=SC1090
set -a
. "$ENV_FILE"
set +a

# Production data must never live in the Git work tree. Deliberately override an
# accidental DATABASE_URL from the private environment file with this fixed path.
DB_PATH="$DATA_DIR/prod.db"
export DATABASE_URL="file:$DB_PATH"
export NODE_ENV=production
export PM2_LOG_DIR="$LOG_DIR"

printf '%s\n' "==> Deploying $DEPLOY_SHA from origin/$DEPLOY_BRANCH"

git -C "$APP_DIR" fetch --prune origin "$DEPLOY_BRANCH"
git -C "$APP_DIR" cat-file -e "$DEPLOY_SHA^{commit}" || fail "Commit is not available after fetch: $DEPLOY_SHA"
git -C "$APP_DIR" merge-base --is-ancestor "$DEPLOY_SHA" "origin/$DEPLOY_BRANCH" \
  || fail "Refusing to deploy $DEPLOY_SHA because it is not reachable from origin/$DEPLOY_BRANCH"

git -C "$APP_DIR" reset --hard "$DEPLOY_SHA"
git -C "$APP_DIR" clean -ffd

cd "$APP_DIR"

printf '%s\n' "==> Installing dependencies"
npm ci --no-audit --no-fund

printf '%s\n' "==> Generating Prisma client"
npx prisma generate

printf '%s\n' "==> Building Next.js application"
npm run build

backup_database() {
  local timestamp backup_path
  timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
  backup_path="$BACKUP_DIR/prod-$timestamp.db"

  printf '%s\n' "==> Backing up SQLite database to $backup_path"
  # SQLite's online backup API avoids copying an inconsistent database while the
  # current PM2 process is still serving writes.
  node - "$DB_PATH" "$backup_path" <<'NODE'
const Database = require("better-sqlite3");

const [sourcePath, destinationPath] = process.argv.slice(2);
const source = new Database(sourcePath, { fileMustExist: true, readonly: true });

(async () => {
  try {
    await source.backup(destinationPath);
  } finally {
    source.close();
  }
})().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
NODE
}

if [[ -f "$DB_PATH" ]]; then
  backup_database
else
  printf '%s\n' "==> No existing SQLite database; skipping backup"
fi

printf '%s\n' "==> Synchronizing schema without accepting data loss"
npx prisma db push --accept-data-loss=false

printf '%s\n' "==> Seeding idempotent application data"
npx tsx prisma/seed.ts

printf '%s\n' "==> Verifying storage"
npx tsx scripts/verify-storage.ts

printf '%s\n' "==> Reloading PM2 application"
pm2 startOrReload "$APP_DIR/ecosystem.config.cjs" --only "$PM2_APP_NAME" --env production --update-env
pm2 save

printf '%s\n' "==> Waiting for health check"
sleep 2
curl --fail --silent --show-error --retry 5 --retry-connrefused --retry-delay 2 \
  "http://127.0.0.1:$PORT/api/papers" >/dev/null
pm2 status "$PM2_APP_NAME"

# Keep the newest backups. Names are generated by this script and contain no
# whitespace, so newline-delimited processing is safe for this controlled path.
if (( BACKUP_KEEP > 0 )); then
  while IFS= read -r stale_backup; do
    rm -f -- "$stale_backup"
  done < <(find "$BACKUP_DIR" -maxdepth 1 -type f -name 'prod-*.db' -printf '%T@ %p\n' \
    | sort -nr \
    | awk -v keep="$BACKUP_KEEP" 'NR > keep { sub(/^[^ ]+ /, ""); print }')
fi

printf '%s\n' "==> Deployment complete: $DEPLOY_SHA"
